## Biblioteca NumPy

In [1]:
# Importação
import numpy as np

In [2]:
# Gerar um NDArray de 2X3
dados = np.random.rand(2, 3)
dados

array([[0.30670976, 0.86831492, 0.49855138],
       [0.23623128, 0.41257009, 0.47702212]])

In [3]:
# Tipo de dados
dados.dtype

dtype('float64')

In [8]:
# Gerando dados zeros
dados_zeros1 = np.zeros(10)
dados_zeros2 = np.zeros(10)
dados_zeros3 = np.zeros(10)
lista_dados = [[dados_zeros1], [dados_zeros2], [dados_zeros3]]
novo_dados = np.array(lista_dados)
novo_dados

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [9]:
# Gerando dados zeros com dimensões 
dados_zeros = np.zeros((10, 10))
dados_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
# Arange
dados_seq = np.arange(0, 50, 3)
dados_seq

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [12]:
# transformando os dados
d_seq_flo = dados_seq.astype(np.float64)
d_seq_flo

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36.,
       39., 42., 45., 48.])